-- core
require("core.options") -- keep first
require("core.keymaps")
require("core.autocmds")
require("core.cmds")

-- plugins
require("plugins.tokyonight")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.mini-surround")
require("plugins.neo-tree")
require("plugins.conform")
require("plugins.snacks")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.persistence")
require("plugins.which-key")
require("plugins.autopairs")
require("plugins.hardtime")
require("plugins.noice")
require("plugins.flash")
require("plugins.dap")
require("plugins.lean")
